export const packageName = "@pickforge/lab-android";

export {
  commonSdkPaths,
  detectAndroidEnvironment,
  detectKvm,
  detectSdkRoot,
  detectSdkTools,
  findSdkTool,
  isValidSystemImageId,
  listSystemImages,
  missingSdkMessage,
  resolveSdkRoot,
  sdkmanagerInstallCommand,
  sdkmanagerPackageInstallCommand,
  systemImageInstalled,
  type AndroidEnvironment,
  type DetectSdkRootOptions,
  type KvmStatus,
  type SdkToolName,
  type SdkToolPaths,
  type SystemImage,
} from "./sdk.js";

export {
  avdDataDir,
  avdExists,
  avdHomeDir,
  avdIniPath,
  avdLockPath,
  avdToolEnv,
  buildCreateAvdArgs,
  createAvd,
  DEFAULT_AVD_NAME,
  listAvds,
  parseEmulatorListAvds,
  readAvdLockOwner,
  scanAvdHome,
  type CreateAvdArgsOptions,
  type CreateAvdOptions,
  type CreateAvdResult,
  type ListAvdsOptions,
} from "./avd.js";

export {
  classifyEmulatorLog,
  describeDeviceState,
  detectBootMode,
  deviceStateHint,
  EmulatorStartError,
  isEmulatorStartError,
  LOG_TAIL_LINES,
  readLogTail,
  startFailureRecord,
  type EmulatorBootMode,
  type EmulatorFailureKind,
  type EmulatorStartDiagnostics,
} from "./diagnostics.js";

export {
  assertConsolePort,
  AUTO_MIN_CONSOLE_PORT,
  buildEmulatorArgs,
  consolePortFromSerial,
  consolePortLockPath,
  emulatorSerial,
  isConsolePortPairFree,
  isTcpPortFree,
  MAX_CONSOLE_PORT,
  MAX_PORT_COLLISION_RETRIES,
  MIN_CONSOLE_PORT,
  pickConsolePort,
  releaseConsolePort,
  startEmulator,
  stopEmulator,
  tryReserveConsolePort,
  waitForBoot,
  type EmulatorArgsOptions,
  type EmulatorHandle,
  type StartEmulatorOptions,
  type StopEmulatorOptions,
  type WaitForBootOptions,
} from "./emulator.js";

export {
  back,
  buildClearLogcatArgs,
  buildInstallApkArgs,
  buildKeyeventArgs,
  buildLaunchAppArgs,
  buildLogcatArgs,
  buildPidofArgs,
  buildResolveLauncherArgs,
  buildScreenshotArgs,
  buildTapArgs,
  buildTypeTextArgs,
  buildUiCatArgs,
  buildUiCleanupArgs,
  buildUiDumpArgs,
  clearLogcat,
  escapeInputText,
  getUiTree,
  home,
  installApk,
  KEYCODE_BACK,
  KEYCODE_HOME,
  launchApp,
  listDevices,
  logcat,
  parseAdbDevices,
  parseResolvedLauncher,
  pressKey,
  resolveAdb,
  runAdb,
  screenshot,
  splitInputText,
  tap,
  typeText,
  UI_DUMP_REMOTE_PATH,
  type AdbDevice,
  type AdbTargetOptions,
  type GetUiTreeOptions,
  type LaunchAppOptions,
  type LaunchAppResult,
  type LogcatArgsOptions,
} from "./adb.js";

export {
  ANDROID_START_FAILURE_META_KEY,
  androidSessionLogDir,
  createAndroidSession,
  destroyAndroidSession,
  getAndroidSessionStatus,
  teardownAndroidSession,
  type AndroidSessionHandle,
  type AndroidSessionOpOptions,
  type AndroidSessionStatus,
  type CreateAndroidSessionOptions,
} from "./session.js";

export { findOnPath } from "./util.js";
