export const packageName = "@pickforge/lab-core";

export { readPickforgeEnv, type EnvLike } from "./env-compat.js";

export {
  buildContainedCommand,
  CONTAINMENT_TOKEN_ENV,
  containmentEnv,
  createContainmentScope,
  destroyContainmentScope,
  ensureContainmentScope,
  listContainedProcesses,
  processCarriesToken,
  readOwnCgroupPath,
  scopeCgroupProblem,
  type ContainedCommand,
  type ContainmentCleanupResult,
  type ContainmentMechanism,
  type ContainmentScope,
  type CreateContainmentScopeOptions,
  type DestroyContainmentOptions,
} from "./containment.js";

export {
  agentsDir,
  ensureDir,
  globalConfigPath,
  isPathConfined,
  isProfileConfined,
  legacyAgentsDirs,
  legacyGlobalConfigPaths,
  legacyPickforgeHomes,
  legacySessionsDirs,
  listDirSafe,
  pickforgeHome,
  projectConfigPath,
  resolveReadablePath,
  runsDir,
  sessionsDir,
  writeFileAtomic,
} from "./paths.js";

export {
  deepMerge,
  isEvidenceEnabled,
  loadConfig,
  readConfigFile,
  resolvedDefaults,
  saveGlobalConfig,
  saveProjectConfig,
  type PickforgeConfig,
  type PickforgeProfile,
  type StorageConfig,
  type StorageMode,
  type ViewerMode,
} from "./config.js";

export {
  canonicalProjectPath,
  deriveProjectId,
  projectId,
  resolveRunStorage,
  StorageConfigError,
  type ResolvedRunStorage,
} from "./storage.js";

export {
  createRun,
  EVIDENCE_ACTION_LOG,
  EVIDENCE_VERSION,
  RunHandle,
  type ArtifactType,
  type CreateRunOptions,
  type RunArtifact,
  type RunManifest,
  type RunStatus,
} from "./run.js";

export {
  listRuns,
  openRunCatalog,
  RunCatalog,
  type RunCatalogEntry,
  type RunCatalogRoot,
} from "./run-catalog.js";

export {
  activePointerPath,
  appendAction,
  beginEvidenceRun,
  clearActivePointer,
  EVIDENCE_MAX_BYTES,
  EVIDENCE_MAX_LINE_BYTES,
  EVIDENCE_RETENTION_KEEP,
  finalizeActiveEvidenceRun,
  isEvidenceRun,
  isEvidenceTruncated,
  isTruncationRecord,
  parseActionsJournal,
  pruneFinalizedEvidenceRuns,
  readActions,
  resolveActivePointer,
  type ActiveEvidenceClaim,
  type ActiveEvidencePointer,
  type AppendActionOptions,
  type AppendOutcome,
  type AppendResult,
  type BeginEvidenceRunOptions,
  type BeginEvidenceRunResult,
  type EvidenceAction,
  type EvidenceActionStatus,
  type EvidenceRecord,
  type EvidenceTruncationRecord,
  type PointerResolution,
  type PruneEvidenceOptions,
} from "./evidence.js";

export {
  EVIDENCE_REPORT,
  renderEvidenceHtml,
  renderRunReport,
  sortEvidenceRecords,
  writeEvidenceReport,
} from "./evidence-render.js";

export { isSecretKey, redactEnv, redactSecrets } from "./redact.js";

export {
  MAX_ERROR_TEXT_LENGTH,
  sanitizeActionTarget,
  sanitizeErrorText,
  sanitizeNetworkFailure,
  sanitizeTypedValue,
  sanitizeUrlForEvidence,
  type SanitizedActionTarget,
  type SanitizedHttpMethod,
  type SanitizedNetworkFailure,
  type SanitizedResourceType,
  type SanitizedTypedValue,
  type TypedInputType,
} from "./evidence-sanitize.js";

export {
  CommandError,
  isPidAlive,
  isProcessGroupAlive,
  listProcessGroupMembers,
  processIdentityMatches,
  readProcessGroupLeaderIdentity,
  readProcessIdentity,
  readProcessStartTicks,
  runCommand,
  startDaemon,
  stopOwnedDaemonGroup,
  stopPid,
  stopProcessGroupVerified,
  type DaemonHandle,
  type OwnedDaemonHandle,
  type ProcessIdentity,
  type RunCommandOptions,
  type RunCommandResult,
  type StartDaemonOptions,
  type StopProcessGroupOutcome,
  type StopProcessGroupResult,
} from "./proc.js";

export {
  captureToTarget,
  requireDisplay,
  resolveConfinedPath,
  resolveDesktopCapableSession,
  resolveRunnableSession,
  resolveScreenshotTarget,
  sessionHasCapability,
  type ResolveConfinedPathOptions,
  type ResolveDesktopCapableSessionOptions,
  type ResolveRunnableSessionOptions,
  type ResolveScreenshotTargetOptions,
  type RunnableSessionType,
  type ScreenshotTarget,
  type SessionCapability,
} from "./target.js";

export {
  createLocalSessions,
  destroyLocalSession,
  destroyLocalSessions,
  localSessionStatusEntry,
  reapDeadRunningSessions,
  teardownLocalSession,
  type AndroidLegHandle,
  type AndroidLiveStatus,
  type BrowserLegHandle,
  type BrowserLiveStatus,
  type DesktopLegHandle,
  type DesktopLiveStatus,
  type DestroyLocalSessionsOptions,
  type DestroyLocalSessionsResult,
  type LocalSessionCreateRuntime,
  type LocalSessionDestroyRuntime,
  type LocalSessionLifecycle,
  type LocalSessionRecipe,
  type LocalSessionStatusEntry,
  type LocalSessionStatusRuntime,
  type LocalSessionSummary,
  type LocalSessionTeardownFinalizer,
  type LocalSessionTeardownRuntime,
} from "./session-lifecycle.js";

export {
  AGENT_PERMITS_DIR,
  HUMAN_LEASE_DRAIN_TIMEOUT_MS,
  HUMAN_LEASE_FILE,
  HUMAN_LEASE_HEARTBEAT_MS,
  HUMAN_LEASE_TTL_MS,
  HumanControlActiveError,
  HumanLeaseDrainTimeoutError,
  HumanLeaseHeldError,
  StaleHumanLeaseError,
  acquireAgentPermit,
  acquireHumanLease,
  checkHumanLeaseBusy,
  clearStaleHumanLease,
  getTakeoverStatus,
  isHumanLeaseStale,
  readHumanLease,
  readHumanLeaseRaw,
  recordTakeoverEvidence,
  releaseAgentPermit,
  releaseHumanLease,
  renewHumanLease,
  withAgentPermit,
  type AcquireHumanLeaseOptions,
  type AgentPermit,
  type HumanLease,
  type HumanLeaseSnapshot,
  type RecordTakeoverEvidenceOptions,
  type TakeoverStatusResult,
} from "./takeover.js";

export {
  REAPER_CLEANUP_PENDING_META_KEY,
  createSession,
  destroySessionRecord,
  getSession,
  isDisplaySocketAlive,
  isSessionProcessAlive,
  listSessions,
  sessionDataDir,
  updateSession,
  type AndroidSessionInfo,
  type BrowserSessionInfo,
  type CreateSessionInput,
  type DesktopSessionInfo,
  type SessionLivenessCheck,
  type SessionRecord,
  type SessionStatus,
  type SessionType,
} from "./session.js";
